### ISSUE TITLE
SElinux policy files in this repo do not match the published files

### ISSUE THREAD

**Issue by ddarwin** [gremlin/selinux-policies#2]
The SElinux policy files, gremlin-openshift3.cil and gremlin-openshift4.cil, do not match the policy files that are referenced in our docs and are downloaded here, https://github.com/gremlin/selinux-policies/releases/download/v0.0.2/selinux-policies-v0.0.2.tar.gz.

**Comment by philgebhardt** [comment]
@ddarwin Are you referring to [gremlin-openshift3.cil](https://github.com/gremlin/selinux-policies/blob/master/policies/gremlin-openshift3.cil) and [gremlin-openshift4.cil](https://github.com/gremlin/selinux-policies/blob/master/policies/gremlin-openshift4.cil)?

If so, that is because these are the source files fed into this projects [build step](https://github.com/gremlin/selinux-policies/blob/master/Makefile#L9-L13). The resulting files in the produced release are a product of this build.
